version: 2
updates:
  - package-ecosystem: "github-actions"
    directory: "/"  # Root directory where workflows are stored
    schedule:
      interval: "monthly"
  - package-ecosystem: "julia"
    directories:
      - "/"
      - "/docs"
    schedule:
      interval: "weekly"
    groups:
      all-julia-packages:
        patterns:
          - "*"
